- resource: render_project
  name: MorphFile
  environments:
    - name: prod
      protected_status: unprotected
      services:
        - name: backend_service_api
          region: ohio
          plan: starter
          runtime_source:
            docker:
              repo_url: https://github.com/Eddie4k-code/MorphFile
              branch: master
              dockerfile_path: ./python/Dockerfile
              context: ./python
      static_sites:
        - name: frontend_morphfile
          repo_url: https://github.com/Eddie4k-code/MorphFile
          branch: master
          root_directory: ./frontend
          publish_path: ./build
          build_command: yarn build


            