- resource: render_project
  name: MorphFile
  environments:
    - name: prod
      protected_status: unprotected
      services:
        - name: backend_service
          region: ohio
          plan: free
          runtime_source:
            docker:
              repo_url: https://github.com/Eddie4k-code/MorphFile
              branch: master
              dockerfile_path: ./python/Dockerfile

            