# Terraform
name: 'Terraform Deploy'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    environment: prod
    env:
      TF_VAR_api_key: ${{ secrets.API_KEY }} 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.7' # Specify the Terraform version

      - name: Initialize Terraform
        run: terraform init -backend-config="conn_str=${{ secrets.CONN_STR }}"

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve